apiVersion: v1
kind: ConfigMap
metadata:
  name: sriovdp-config
  namespace: kube-system
data:
  config.json: |
    {
        "resourceList": [{
                "resourceName": "x700_gtp",
                "resourcePrefix": "intel.com",
                "selectors": [{
                    "vendors": ["8086"],
                    "devices": ["154c"],
                    "ddpProfiles": ["GTPv1-C/U IPv4/IPv6 payload"]
                }]
            },
            {
                "resourceName": "x700_pppoe",
                "resourcePrefix": "intel.com",
                "selectors": [{
                    "vendors": ["8086"],
                    "devices": ["154c"],
                    "ddpProfiles": ["E710 PPPoE and PPPoL2TPv2"]
                }]
            }
        ]
    }
