apiVersion: v1
kind: ConfigMap
metadata:
  name: sriovdp-config
  namespace: kube-system
data:
  config.json: |
    {
        "resourceList": [
            {
                "resourceName": "mlnx_rdma",
                "resourcePrefix": "mellanox.com",
                "selectors": [{
                    "vendors": ["15b3"],
                    "devices": ["1016", "1018"],
                    "drivers": ["mlx5_core"],
                    "isRdma": true
                }]
            },
            {
              "resourceName": "intel_rdma",
                "selectors": {
                    "vendors": ["8086"],
                    "devices": ["1889"],
                    "drivers": ["iavf"],
                    "isRdma": true
                }
            }
        ]
    }
