apiVersion: v1
kind: Pod
metadata:
  name: rdma-app
  annotations:
    k8s.v1.cni.cncf.io/networks: sriov-rdma-mlnx
spec:
  containers:
  - name: testpmd
    image: <RDMA image>
    imagePullPolicy: Never
    securityContext:
     capabilities:
        add: ["IPC_LOCK"]
    resources:
      requests:
        mellanox.com/mlnx_rdma: 2
      limits:
        mellanox.com/mlnx_rdma: 2
    command: ["sleep", "infinity"]
