---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rbln-device-plugin
  namespace: kube-system

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: rbln-device-plugin
  namespace: kube-system
  labels:
    tier: node
    app: rbln-device-plugin
spec:
  selector:
    matchLabels:
      name: rbln-device-plugin
  template:
    metadata:
      labels:
        name: rbln-device-plugin
        tier: node
        app: rbln-device-plugin
    spec:
      hostNetwork: true
      nodeSelector:
        kubernetes.io/arch: amd64
      tolerations:
        - key: ""
          operator: Exists
          effect: NoSchedule
        - key: ""
          operator: Exists
          effect: NoExecute
      serviceAccountName: rbln-device-plugin
      containers:
        - name: device-plugin
          image: rebellions/k8s-device-plugin:v0.3.0
          imagePullPolicy: IfNotPresent
          args:
            - --log-dir=device-plugin
            - --log-level=10
          securityContext:
            privileged: true
            runAsUser: 0
          resources:
            requests:
              cpu: "250m"
              memory: "40Mi"
            limits:
              cpu: 1
              memory: "200Mi"
          volumeMounts:
            - name: devicesock
              mountPath: /var/lib/kubelet/device-plugins
              readOnly: false
            - name: plugins-registry
              mountPath: /var/lib/kubelet/plugins_registry
              readOnly: false
            - name: log
              mountPath: /var/log
            - name: config-volume
              mountPath: /etc/pcidp
            - name: device-info
              mountPath: /var/run/k8s.cni.cncf.io/devinfo/dp
            - name: host-usr-local-bin
              mountPath: /usr/local/bin
              readOnly: true
            - name: host-dev
              mountPath: /dev
            - name: host-sys
              mountPath: /sys
      volumes:
        - name: devicesock
          hostPath:
            path: /var/lib/kubelet/device-plugins
        - name: plugins-registry
          hostPath:
            path: /var/lib/kubelet/plugins_registry
        - name: log
          hostPath:
            path: /var/log
        - name: device-info
          hostPath:
            path: /var/run/k8s.cni.cncf.io/devinfo/dp
            type: DirectoryOrCreate
        - name: config-volume
          configMap:
            name: rbln-device-plugin-config
            items:
              - key: config.json
                path: config.json
        - name: host-sys
          hostPath:
            path: /sys
            type: Directory
        - name: host-dev
          hostPath:
            path: /dev
            type: Directory
        - name: host-usr-local-bin
          hostPath:
            path: /usr/local/bin
            type: Directory
