apiVersion: v1
kind: ConfigMap
metadata:
  name: sriovdp-config
  namespace: kube-system
data:
  config.json: |
    {
        "resourceList": [{
                "resourceName": "e800_default",
                "resourcePrefix": "intel.com",
                "selectors": [{
                    "vendors": ["8086"],
                    "devices": ["1889"],
                    "ddpProfiles": ["ICE OS Default Package"]
                }]
            },
            {
                "resourceName": "e800_comms",
                "resourcePrefix": "intel.com",
                "selectors": [{
                    "vendors": ["8086"],
                    "devices": ["1889"],
                    "ddpProfiles": ["ICE COMMS Package"]
                }]
            }
       ]
    }
