name: Push images to rebellions registry

on:
  push:
    branches:
      - master
env:
  IMAGE_NAME: rebellions/k8s-device-plugin

jobs:
  build-and-push-amd64-device-plugin:
    name: Image push AMD64
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest-amd64
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
          file: images/Dockerfile

  push-manifest:
    runs-on: ubuntu-latest
    needs: [build-and-push-amd64-device-plugin]
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Create manifest for multi-arch images
        run: |
          docker buildx imagetools create -t ${{ env.IMAGE_NAME }}:latest \
          ${{ env.IMAGE_NAME }}:latest-amd64
